const ENV = {
  // SERVER
  PORT: process.env.PORT || 8000,
  CORS_ORIGIN: process.env.CORS_ORIGIN,

  // FRONTEND (CLIENT)
  FRONTEND_BASE_URL: process.env.FRONTEND_BASE_URL,

  // ACCESS AND REFRESH TOKEN
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET || '6roe54cj4a74q7qi45l',
  ACCESS_TOKEN_EXPIRY: process.env.ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET || 'viystdmoowdvoclzcokc',
  REFRESH_TOKEN_EXPIRY: process.env.REFRESH_TOKEN_EXPIRY,

  // GOOGLE
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || '',
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET || '',
  GOOGLE_CALLBACK_URL: process.env.GOOGLE_CALLBACK_URL || '',

  // FACEBOOK
  FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID || '',
  FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET || '',
  FACEBOOK_CALLBACK_URL: process.env.FACEBOOK_CALLBACK_URL || '',

  // NODEMAILER
  NODEMAILER_HOST: process.env.NODEMAILER_HOST || '',
  NODEMAILER_PORT: process.env.NODEMAILER_PORT || '',
  NODEMAILER_USER_NAME: process.env.NODEMAILER_USER_NAME || '',
  NODEMAILER_USER_EMAIL: process.env.NODEMAILER_USER_EMAIL || '',
  NODEMAILER_USER_PASSWORD: process.env.NODEMAILER_USER_PASSWORD || '',

  // AWS
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID || '',
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY || '',
  AWS_S3_BUCKET_NAME: process.env.AWS_S3_BUCKET_NAME || '',
  AWS_REGION: process.env.AWS_REGION || '',

  // RTMP SERVER
  RTMP_SERVER_URL: process.env.RTMP_SERVER_URL || '',
}

export default ENV
